[project]
name = "scrapling-first-step"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "scrapling[all]>=0.4.7",
    "sqlalchemy>=2.0.49",
]

[dependency-groups]
dev = [
    "ruff>=0.15.11",
    "tryke>=0.0.27",
]

[tool.ruff]
line-length = 88
indent-width = 2

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "T201",
    "COM812",
    "ISC001",
    "D415",
    "RUF002",
    "RUF003",
]
unfixable = [
    "F401",
    "F841",
]
pydocstyle.convention = "google"

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "D",
    "S101",
    "N802",
    "ARG",
]

[tool.ruff.lint.pylint]
max-args = 6
