"""add description and many-to-many tables

Revision ID: c063d46ddd0b
Revises: 
Create Date: 2026-05-22 18:10:42.038914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c063d46ddd0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purposes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subsidy_purposes',
    sa.Column('subsidy_id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ),
    sa.ForeignKeyConstraint(['subsidy_id'], ['subsidies.id'], ),
    sa.PrimaryKeyConstraint('subsidy_id', 'purpose_id')
    )
    op.create_table('subsidy_target_businesses',
    sa.Column('subsidy_id', sa.Integer(), nullable=False),
    sa.Column('target_business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subsidy_id'], ['subsidies.id'], ),
    sa.ForeignKeyConstraint(['target_business_id'], ['target_businesses.id'], ),
    sa.PrimaryKeyConstraint('subsidy_id', 'target_business_id')
    )
    op.create_table('subsidy_target_expenses',
    sa.Column('subsidy_id', sa.Integer(), nullable=False),
    sa.Column('target_expense_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subsidy_id'], ['subsidies.id'], ),
    sa.ForeignKeyConstraint(['target_expense_id'], ['target_expenses.id'], ),
    sa.PrimaryKeyConstraint('subsidy_id', 'target_expense_id')
    )
    op.add_column('subsidies', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsidies', 'description')
    op.drop_table('subsidy_target_expenses')
    op.drop_table('subsidy_target_businesses')
    op.drop_table('subsidy_purposes')
    op.drop_table('target_expenses')
    op.drop_table('target_businesses')
    op.drop_table('purposes')
    # ### end Alembic commands ###
